## Processing : Unsupervised

In [1]:
### autoreloader
%load_ext autoreload
%autoreload 2

In [2]:
### setting up the system path
import sys
sys.path.append('../')

In [3]:
### importing the functions from the src
from src.basic.basic_processing import load_data, check_nan_duplicates_shape, split_target_feature, save_data

##### working with the train data

In [10]:
### setting up the data path
train_distance_path = '../data/processed/train_distance.csv'

In [11]:
### loading the data
train_distance = load_data(train_distance_path)
train_distance.head()

,Transaction_Type_Bank Transfer,Transaction_Type_Online,Transaction_Type_POS,Device_Type_Mobile,Device_Type_Tablet,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Merchant_Category_Electronics,...,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Fraud_Label,Timestamp_month,Timestamp_day,Timestamp_hour,Transaction_Amount_boxcox
0,0,0,0,0,1,0,0,0,0,0,...,1.00,0.592437,0.734863,0.366737,0,1,0.272727,0.400000,0.695652,0.424444
1,1,0,0,1,0,0,1,0,0,1,...,0.25,0.130252,0.159358,0.486549,0,0,0.181818,0.866667,0.217391,0.577225
2,0,0,0,0,1,0,0,1,0,1,...,0.50,0.848739,0.457245,0.296030,1,0,0.727273,0.866667,1.000000,0.254520
3,0,1,0,1,0,0,0,0,0,0,...,0.50,0.571429,0.985009,0.336134,0,0,0.727273,0.300000,0.565217,0.490544
4,0,1,0,1,0,0,0,1,0,0,...,0.25,0.029412,0.984885,0.080308,0,0,0.000000,0.400000,0.260870,0.307802

In [12]:
### checking the nan_duplicates_shape
check_nan_duplicates_shape(train_distance)

Shape : (40000, 34)
Duplicates : 0 \Transaction_Type_Bank Transfer    0
Transaction_Type_Online           0
Transaction_Type_POS              0
Device_Type_Mobile                0
Device_Type_Tablet                0
Location_Mumbai                   0
Location_New York                 0
Location_Sydney                   0
Location_Tokyo                    0
Merchant_Category_Electronics     0
Merchant_Category_Groceries       0
Merchant_Category_Restaurants     0
Merchant_Category_Travel          0
Card_Type_Discover                0
Card_Type_Mastercard              0
Card_Type_Visa                    0
Authentication_Method_OTP         0
Authentication_Method_PIN         0
Authentication_Method_Password    0
Account_Balance                   0
IP_Address_Flag                   0
Previous_Fraudulent_Activity      0
Daily_Transaction_Count           0
Avg_Transaction_Amount_7d         0
Failed_Transaction_Count_7d       0
Card_Age                          0
Transaction_Distance              0
Risk_Score                        0
Is_Weekend                        0
Fraud_Label                       0
Timestamp_month                   0
Timestamp_day                     0
Timestamp_hour                    0
Transaction_Amount_boxcox         0
dtype: int64

In [21]:
### separating the target_feature
train, y_train_true = split_target_feature(train_distance, target_feature = 'Fraud_Label')

In [20]:
### checking out the both
train.head()

,Transaction_Type_Bank Transfer,Transaction_Type_Online,Transaction_Type_POS,Device_Type_Mobile,Device_Type_Tablet,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Merchant_Category_Electronics,...,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Timestamp_month,Timestamp_day,Timestamp_hour,Transaction_Amount_boxcox
0,0,0,0,0,1,0,0,0,0,0,...,0.209694,1.00,0.592437,0.734863,0.366737,0,0.272727,0.400000,0.695652,0.424444
1,1,0,0,1,0,0,1,0,0,1,...,0.387653,0.25,0.130252,0.159358,0.486549,0,0.181818,0.866667,0.217391,0.577225
2,0,0,0,0,1,0,0,1,0,1,...,0.458673,0.50,0.848739,0.457245,0.296030,1,0.727273,0.866667,1.000000,0.254520
3,0,1,0,1,0,0,0,0,0,0,...,0.683633,0.50,0.571429,0.985009,0.336134,0,0.727273,0.300000,0.565217,0.490544
4,0,1,0,1,0,0,0,1,0,0,...,0.911776,0.25,0.029412,0.984885,0.080308,0,0.000000,0.400000,0.260870,0.307802

In [22]:
### target_feature
y_train_true.head()

0    1
1    0
2    0
3    0
4    0
Name: Fraud_Label, dtype: int64

In [23]:
### saving the both data
train_path = '../data/unsupervised_ready/train.csv'
y_train_true_path = '../data/unsupervised_ready/y_train_true.csv'
save_data(train, train_path)
save_data(y_train_true, y_train_true_path)

In [24]:
### checking up on the both
train = load_data(train_path)
train.head()

,Transaction_Type_Bank Transfer,Transaction_Type_Online,Transaction_Type_POS,Device_Type_Mobile,Device_Type_Tablet,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Merchant_Category_Electronics,...,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Timestamp_month,Timestamp_day,Timestamp_hour,Transaction_Amount_boxcox
0,0,0,0,0,1,0,0,0,0,0,...,0.209694,1.00,0.592437,0.734863,0.366737,0,0.272727,0.400000,0.695652,0.424444
1,1,0,0,1,0,0,1,0,0,1,...,0.387653,0.25,0.130252,0.159358,0.486549,0,0.181818,0.866667,0.217391,0.577225
2,0,0,0,0,1,0,0,1,0,1,...,0.458673,0.50,0.848739,0.457245,0.296030,1,0.727273,0.866667,1.000000,0.254520
3,0,1,0,1,0,0,0,0,0,0,...,0.683633,0.50,0.571429,0.985009,0.336134,0,0.727273,0.300000,0.565217,0.490544
4,0,1,0,1,0,0,0,1,0,0,...,0.911776,0.25,0.029412,0.984885,0.080308,0,0.000000,0.400000,0.260870,0.307802

In [25]:
### y_true_train
y_train_true = load_data(y_train_true_path)
y_train_true.head()

   Fraud_Label
0            1
1            0
2            0
3            0
4            0

##### loading the valid data, checking and changing it's name

In [16]:
### setting up the path
valid_distance_path = '../data/processed/valid_distance.csv'

In [17]:
### loading the data
valid_distance = load_data(valid_distance_path)
valid_distance.head()

,Transaction_Type_Bank Transfer,Transaction_Type_Online,Transaction_Type_POS,Device_Type_Mobile,Device_Type_Tablet,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Merchant_Category_Electronics,...,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Timestamp_month,Timestamp_day,Timestamp_hour,Transaction_Amount_boxcox
0,0,1,0,1,0,0,0,1,0,0,...,0.694722,0.75,0.894958,0.913818,0.686537,1,0.090909,0.300000,0.086957,0.265145
1,1,0,0,1,0,0,1,0,0,0,...,0.075779,0.25,0.323529,0.059363,0.532206,1,0.181818,0.833333,0.956522,0.371321
2,0,0,0,0,0,0,0,0,1,0,...,0.306400,0.50,0.243697,0.958614,0.492398,0,0.636364,0.133333,0.521739,0.324475
3,0,0,1,0,1,1,0,0,0,0,...,0.674252,1.00,0.596639,0.663668,0.550310,0,0.000000,0.700000,0.826087,0.336945
4,1,0,0,0,1,0,0,1,0,0,...,0.285297,0.00,0.949580,0.114540,0.220744,0,0.636364,0.633333,0.521739,0.407352

In [18]:
### verification
check_nan_duplicates_shape(valid_distance)

Shape : (10000, 33)
Duplicates : 0 \Transaction_Type_Bank Transfer    0
Transaction_Type_Online           0
Transaction_Type_POS              0
Device_Type_Mobile                0
Device_Type_Tablet                0
Location_Mumbai                   0
Location_New York                 0
Location_Sydney                   0
Location_Tokyo                    0
Merchant_Category_Electronics     0
Merchant_Category_Groceries       0
Merchant_Category_Restaurants     0
Merchant_Category_Travel          0
Card_Type_Discover                0
Card_Type_Mastercard              0
Card_Type_Visa                    0
Authentication_Method_OTP         0
Authentication_Method_PIN         0
Authentication_Method_Password    0
Account_Balance                   0
IP_Address_Flag                   0
Previous_Fraudulent_Activity      0
Daily_Transaction_Count           0
Avg_Transaction_Amount_7d         0
Failed_Transaction_Count_7d       0
Card_Age                          0
Transaction_Distance              0
Risk_Score                        0
Is_Weekend                        0
Timestamp_month                   0
Timestamp_day                     0
Timestamp_hour                    0
Transaction_Amount_boxcox         0
dtype: int64

In [26]:
### changing the name and saving it at correct location
valid = valid_distance.copy()
valid.head()

,Transaction_Type_Bank Transfer,Transaction_Type_Online,Transaction_Type_POS,Device_Type_Mobile,Device_Type_Tablet,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Merchant_Category_Electronics,...,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Timestamp_month,Timestamp_day,Timestamp_hour,Transaction_Amount_boxcox
0,0,1,0,1,0,0,0,1,0,0,...,0.694722,0.75,0.894958,0.913818,0.686537,1,0.090909,0.300000,0.086957,0.265145
1,1,0,0,1,0,0,1,0,0,0,...,0.075779,0.25,0.323529,0.059363,0.532206,1,0.181818,0.833333,0.956522,0.371321
2,0,0,0,0,0,0,0,0,1,0,...,0.306400,0.50,0.243697,0.958614,0.492398,0,0.636364,0.133333,0.521739,0.324475
3,0,0,1,0,1,1,0,0,0,0,...,0.674252,1.00,0.596639,0.663668,0.550310,0,0.000000,0.700000,0.826087,0.336945
4,1,0,0,0,1,0,0,1,0,0,...,0.285297,0.00,0.949580,0.114540,0.220744,0,0.636364,0.633333,0.521739,0.407352

In [27]:
### saving the data
valid_path = '../data/unsupervised_ready/valid.csv'
save_data(valid, valid_path)

In [28]:
### loading it up again to verify if everything went well
valid = load_data(valid_path)
valid.head()

,Transaction_Type_Bank Transfer,Transaction_Type_Online,Transaction_Type_POS,Device_Type_Mobile,Device_Type_Tablet,Location_Mumbai,Location_New York,Location_Sydney,Location_Tokyo,Merchant_Category_Electronics,...,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Timestamp_month,Timestamp_day,Timestamp_hour,Transaction_Amount_boxcox
0,0,1,0,1,0,0,0,1,0,0,...,0.694722,0.75,0.894958,0.913818,0.686537,1,0.090909,0.300000,0.086957,0.265145
1,1,0,0,1,0,0,1,0,0,0,...,0.075779,0.25,0.323529,0.059363,0.532206,1,0.181818,0.833333,0.956522,0.371321
2,0,0,0,0,0,0,0,0,1,0,...,0.306400,0.50,0.243697,0.958614,0.492398,0,0.636364,0.133333,0.521739,0.324475
3,0,0,1,0,1,1,0,0,0,0,...,0.674252,1.00,0.596639,0.663668,0.550310,0,0.000000,0.700000,0.826087,0.336945
4,1,0,0,0,1,0,0,1,0,0,...,0.285297,0.00,0.949580,0.114540,0.220744,0,0.636364,0.633333,0.521739,0.407352