## Combining data : Model ready data

In [1]:
### autoreloader
%load_ext autoreload
%autoreload 2

In [2]:
### setting up the system path
import sys
sys.path.append('../')

In [3]:
### importing the functions from the src file
from src.data.load_data import load_data, get_nan_duplicates_shape, get_shape, drop_col, save_data
from src.processing.combine_features import combine_features

##### ******* train data ********

In [4]:
### setting up the path
cat_train_processed_path = '../data/intermidiate/cat_train_processed.csv'
num_train_processed_path = '../data/intermidiate/num_train_processed.csv'
num_train_processed_scaled_path = '../data/intermidiate/num_train_processed_scaled.csv'

In [5]:
### loading and checking the 'cat_train_processed'
cat_train_processed = load_data(cat_train_processed_path)
cat_train_processed.head()

   Transaction_Type_Bank Transfer  ...  Authentication_Method_Password
0                               0  ...                               0
1                               1  ...                               0
2                               0  ...                               0
3                               0  ...                               0
4                               0  ...                               1

[5 rows x 19 columns]

In [6]:
### loading and checking the 'num_train_processed'
num_train_processed = load_data(num_train_processed_path)
num_train_processed.head()

   Transaction_Amount  Account_Balance  ...  Timestamp_day  Timestamp_hour
0               80.39         32068.28  ...             13              16
1              196.60         94961.81  ...             27               5
2               21.88         39354.55  ...             27              23
3              121.23         46138.99  ...             10              13
4               34.53         52750.58  ...             13               6

[5 rows x 15 columns]

In [9]:
### loading and checking the 'num_train_processed_scaled'
num_train_processed_scaled = load_data(num_train_processed_scaled_path)
num_train_processed_scaled.head()

   Account_Balance  IP_Address_Flag  ...  Timestamp_hour  Transaction_Amount_boxcox
0         0.317272                0  ...        0.695652                   0.424444
1         0.949384                0  ...        0.217391                   0.577225
2         0.390503                0  ...        1.000000                   0.254520
3         0.458690                0  ...        0.565217                   0.490544
4         0.525140                0  ...        0.260870                   0.307802

[5 rows x 15 columns]

In [11]:
### combining the data for the trees
train_tree = combine_features(cat_train_processed, num_train_processed)
train_tree.head()

   Transaction_Type_Bank Transfer  ...  Timestamp_hour
0                               0  ...              16
1                               1  ...               5
2                               0  ...              23
3                               0  ...              13
4                               0  ...               6

[5 rows x 34 columns]

In [12]:
### checking the shape
get_shape(train_tree)

(40000, 34)

In [14]:
### combining the data for the distance based models
train_distance = combine_features(cat_train_processed, num_train_processed_scaled)
train_distance.head()

   Transaction_Type_Bank Transfer  ...  Transaction_Amount_boxcox
0                               0  ...                   0.424444
1                               1  ...                   0.577225
2                               0  ...                   0.254520
3                               0  ...                   0.490544
4                               0  ...                   0.307802

[5 rows x 34 columns]

In [15]:
### checking the shape
get_shape(train_distance)

(40000, 34)

In [16]:
### setting up the path and saving the 'model_ready' train data
train_tree_path = '../data/model_ready/train_tree.csv'
train_distance_path = '../data/model_ready/train_distance.csv'

In [17]:
### saving up the data
save_data(train_tree, train_tree_path)
save_data(train_distance, train_distance_path)

In [18]:
### check for the  verification of the saved data
train_tree = load_data(train_tree_path)
train_tree.head()

   Transaction_Type_Bank Transfer  ...  Timestamp_hour
0                               0  ...              16
1                               1  ...               5
2                               0  ...              23
3                               0  ...              13
4                               0  ...               6

[5 rows x 34 columns]

In [19]:
### check for the 'train_distance' 
train_distance = load_data(train_distance_path)
train_distance.head()

   Transaction_Type_Bank Transfer  ...  Transaction_Amount_boxcox
0                               0  ...                   0.424444
1                               1  ...                   0.577225
2                               0  ...                   0.254520
3                               0  ...                   0.490544
4                               0  ...                   0.307802

[5 rows x 34 columns]

##### ********** valid data ***********

In [20]:
### setting up the path
cat_valid_processed_path = '../data/intermidiate/cat_valid_processed.csv'
num_valid_processed_path = '../data/intermidiate/num_valid_processed.csv'
num_valid_processed_scaled_path = '../data/intermidiate/num_valid_processed_scaled.csv'

In [21]:
### loading and checking the 'cat_valid_processed'
cat_valid_processed = load_data(cat_valid_processed_path)
cat_valid_processed.head()

   Transaction_Type_Bank Transfer  ...  Authentication_Method_Password
0                               0  ...                               0
1                               1  ...                               1
2                               0  ...                               1
3                               0  ...                               0
4                               1  ...                               0

[5 rows x 19 columns]

In [22]:
### loading and checking the 'num_valid_processed'
num_valid_processed = load_data(num_valid_processed_path)
num_valid_processed.head()

   Transaction_Amount  Account_Balance  ...  Timestamp_day  Timestamp_hour
0               19.98          1804.81  ...             10               2
1               45.32         46648.03  ...             26              22
2               32.25         80244.56  ...              5              12
3               35.41         24611.99  ...             22              19
4               57.80         27154.09  ...             20              12

[5 rows x 14 columns]

In [23]:
### loading and checking the 'num_valid_processed_scaled'
num_valid_processed_scaled = load_data(num_valid_processed_scaled_path)
num_valid_processed_scaled.head()

   Account_Balance  IP_Address_Flag  ...  Timestamp_hour  Transaction_Amount_boxcox
0         0.012998                0  ...        0.086957                   0.265145
1         0.463744                0  ...        0.956522                   0.371321
2         0.801443                0  ...        0.521739                   0.324475
3         0.242247                0  ...        0.826087                   0.336945
4         0.267799                1  ...        0.521739                   0.407352

[5 rows x 14 columns]

In [24]:
### combining the features for the tree based models
valid_tree = combine_features(cat_valid_processed, num_valid_processed)
valid_tree.head()

   Transaction_Type_Bank Transfer  ...  Timestamp_hour
0                               0  ...               2
1                               1  ...              22
2                               0  ...              12
3                               0  ...              19
4                               1  ...              12

[5 rows x 33 columns]

In [25]:
### combining the features for the distance based models
valid_distance = combine_features(cat_valid_processed, num_valid_processed_scaled)
valid_distance.head()

   Transaction_Type_Bank Transfer  ...  Transaction_Amount_boxcox
0                               0  ...                   0.265145
1                               1  ...                   0.371321
2                               0  ...                   0.324475
3                               0  ...                   0.336945
4                               1  ...                   0.407352

[5 rows x 33 columns]

In [26]:
### setting up the path and saving the 'model_ready' train data
valid_tree_path = '../data/model_ready/valid_tree.csv'
valid_distance_path = '../data/model_ready/valid_distance.csv'

In [27]:
### saving up the data
save_data(valid_tree, valid_tree_path)
save_data(valid_distance, valid_distance_path)

In [28]:
### checking for the 'valid_tree'
valid_tree = load_data(valid_tree_path)
valid_tree.head()

   Transaction_Type_Bank Transfer  ...  Timestamp_hour
0                               0  ...               2
1                               1  ...              22
2                               0  ...              12
3                               0  ...              19
4                               1  ...              12

[5 rows x 33 columns]

In [29]:
### checking for the 'valid_distance'
valid_distance = load_data(valid_distance_path)
valid_distance.head()

   Transaction_Type_Bank Transfer  ...  Transaction_Amount_boxcox
0                               0  ...                   0.265145
1                               1  ...                   0.371321
2                               0  ...                   0.324475
3                               0  ...                   0.336945
4                               1  ...                   0.407352

[5 rows x 33 columns]