## Split features : categorical and numerical columns

In [1]:
### autoreloader
%load_ext autoreload
%autoreload 2

In [2]:
### setting up the path
import sys
sys.path.append('../')

In [3]:
from src.data.load_data import load_data, get_info, get_nan_duplicates_shape, get_shape, get_unique, get_value_counts, save_data, drop_col
from src.processing.split_features import split_feature

In [4]:
### setting up the data path
train_path = '../data/split/train.csv'
valid_path = '../data/split/valid.csv'

##### *************** Train data *****************

In [5]:
### loading up and veryfying the train data
df_train = load_data(train_path)
df_train.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,80.39,ATM Withdrawal,2023-04-13 16:02:00,32068.28,Tablet,London,Travel,0,0,5,112.75,4,Mastercard,142,3674.33,PIN,0.3668,0,1
1,196.60,Bank Transfer,2023-03-27 05:02:00,94961.81,Mobile,New York,Electronics,0,0,8,199.95,1,Visa,32,796.99,OTP,0.4866,0,0
2,21.88,ATM Withdrawal,2023-09-27 23:30:00,39354.55,Tablet,Sydney,Electronics,0,0,7,234.75,2,Mastercard,203,2286.33,OTP,0.2961,1,0
3,121.23,Online,2023-09-10 13:13:00,46138.99,Mobile,London,Travel,0,0,8,344.98,2,Discover,137,4924.98,PIN,0.3362,0,0
4,34.53,Online,2023-01-13 06:58:00,52750.58,Mobile,Sydney,Groceries,0,0,6,456.77,1,Amex,8,4924.36,Password,0.0804,0,0

In [6]:
### veryfying the shape
get_shape(df_train)

(40000, 19)

In [6]:
### veryfying the nan values
get_nan_duplicates_shape(df_train)

shape : (40000, 19)
duplicate values : 0
Transaction_Amount              0
Transaction_Type                0
Timestamp                       0
Account_Balance                 0
Device_Type                     0
Location                        0
Merchant_Category               0
IP_Address_Flag                 0
Previous_Fraudulent_Activity    0
Daily_Transaction_Count         0
Avg_Transaction_Amount_7d       0
Failed_Transaction_Count_7d     0
Card_Type                       0
Card_Age                        0
Transaction_Distance            0
Authentication_Method           0
Risk_Score                      0
Is_Weekend                      0
Fraud_Label                     0
dtype: int64

In [8]:
### get info
get_info(df_train)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Transaction_Amount            40000 non-null  float64
 1   Transaction_Type              40000 non-null  object
 2   Timestamp                     40000 non-null  object
 3   Account_Balance               40000 non-null  float64
 4   Device_Type                   40000 non-null  object
 5   Location                      40000 non-null  object
 6   Merchant_Category             40000 non-null  object
 7   IP_Address_Flag               40000 non-null  int64
 8   Previous_Fraudulent_Activity  40000 non-null  int64
 9   Daily_Transaction_Count       40000 non-null  int64
 10  Avg_Transaction_Amount_7d     40000 non-null  float64
 11  Failed_Transaction_Count_7d   40000 non-null  int64
 12  Card_Type                     40000 non-null  object
 13  Card_Age                      40000 non-null  int64
 14  Transaction_Distance          40000 non-null  float64
 15  Authentication_Method         40000 non-null  object
 16  Risk_Score                    40000 non-null  float64
 17  Is_Weekend                    40000 non-null  int64
 18  Fraud_Label                   40000 non-null  int64
dtypes: float64(5), int64(7), object(7)
memory usage: 5.8+ MB

In [9]:
### splitting the categorical and numerical columns
cat_cols_train, num_cols_train = split_feature(df_train, force_num = ['Timestamp'])

In [10]:
### veryfying the split
cat_cols_train.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,ATM Withdrawal,Tablet,London,Travel,Mastercard,PIN
1,Bank Transfer,Mobile,New York,Electronics,Visa,OTP
2,ATM Withdrawal,Tablet,Sydney,Electronics,Mastercard,OTP
3,Online,Mobile,London,Travel,Discover,PIN
4,Online,Mobile,Sydney,Groceries,Amex,Password

In [11]:
### get shape
get_shape(cat_cols_train)

(40000, 6)

In [12]:
### veryfying the numerical column split
num_cols_train.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Fraud_Label,Timestamp
0,80.39,32068.28,0,0,5,112.75,4,142,3674.33,0.3668,0,1,2023-04-13 16:02:00
1,196.60,94961.81,0,0,8,199.95,1,32,796.99,0.4866,0,0,2023-03-27 05:02:00
2,21.88,39354.55,0,0,7,234.75,2,203,2286.33,0.2961,1,0,2023-09-27 23:30:00
3,121.23,46138.99,0,0,8,344.98,2,137,4924.98,0.3362,0,0,2023-09-10 13:13:00
4,34.53,52750.58,0,0,6,456.77,1,8,4924.36,0.0804,0,0,2023-01-13 06:58:00

In [13]:
### get shape
get_shape(num_cols_train)

(40000, 13)

##### *************** Valid data *****************

In [8]:
### loading the data
df_valid = load_data(valid_path)
df_valid.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend
0,19.98,Online,2023-02-10 02:49:00,1804.81,Mobile,Sydney,Clothing,0,0,2,350.41,3,Mastercard,214,4568.48,OTP,0.6865,1
1,45.32,Bank Transfer,2023-03-26 22:32:00,46648.03,Mobile,New York,Travel,0,1,11,47.14,1,Amex,78,297.39,Password,0.5322,1
2,32.25,ATM Withdrawal,2023-08-05 12:29:00,80244.56,Laptop,Tokyo,Restaurants,0,0,7,160.14,2,Amex,59,4792.40,Password,0.4924,0
3,35.41,POS,2023-01-22 19:26:00,24611.99,Tablet,Mumbai,Travel,0,0,3,340.38,4,Mastercard,143,3318.08,OTP,0.5503,0
4,57.80,Bank Transfer,2023-08-20 12:11:00,27154.09,Tablet,Sydney,Groceries,1,0,1,149.80,0,Visa,227,573.20,Biometric,0.2208,0

In [15]:
### checking the shape
get_shape(df_valid)

(10000, 18)

In [9]:
### veryfying the nan
get_nan_duplicates_shape(df_valid)

shape : (10000, 18)
duplicate values : 0
Transaction_Amount              0
Transaction_Type                0
Timestamp                       0
Account_Balance                 0
Device_Type                     0
Location                        0
Merchant_Category               0
IP_Address_Flag                 0
Previous_Fraudulent_Activity    0
Daily_Transaction_Count         0
Avg_Transaction_Amount_7d       0
Failed_Transaction_Count_7d     0
Card_Type                       0
Card_Age                        0
Transaction_Distance            0
Authentication_Method           0
Risk_Score                      0
Is_Weekend                      0
dtype: int64

In [17]:
### veryfying the info
get_info(df_valid)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Transaction_Amount            10000 non-null  float64
 1   Transaction_Type              10000 non-null  object
 2   Timestamp                     10000 non-null  object
 3   Account_Balance               10000 non-null  float64
 4   Device_Type                   10000 non-null  object
 5   Location                      10000 non-null  object
 6   Merchant_Category             10000 non-null  object
 7   IP_Address_Flag               10000 non-null  int64
 8   Previous_Fraudulent_Activity  10000 non-null  int64
 9   Daily_Transaction_Count       10000 non-null  int64
 10  Avg_Transaction_Amount_7d     10000 non-null  float64
 11  Failed_Transaction_Count_7d   10000 non-null  int64
 12  Card_Type                     10000 non-null  object
 13  Card_Age                      10000 non-null  int64
 14  Transaction_Distance          10000 non-null  float64
 15  Authentication_Method         10000 non-null  object
 16  Risk_Score                    10000 non-null  float64
 17  Is_Weekend                    10000 non-null  int64
dtypes: float64(5), int64(6), object(7)
memory usage: 1.4+ MB

In [18]:
### making the split
cat_cols_valid, num_cols_valid = split_feature(df_valid, force_num = ['Timestamp'])

In [19]:
### veryfying the both
cat_cols_valid.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,Online,Mobile,Sydney,Clothing,Mastercard,OTP
1,Bank Transfer,Mobile,New York,Travel,Amex,Password
2,ATM Withdrawal,Laptop,Tokyo,Restaurants,Amex,Password
3,POS,Tablet,Mumbai,Travel,Mastercard,OTP
4,Bank Transfer,Tablet,Sydney,Groceries,Visa,Biometric

In [21]:
### veryfying the shape
get_shape(cat_cols_valid)

(10000, 6)

In [22]:
### num_cols_valid
num_cols_valid.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Timestamp
0,19.98,1804.81,0,0,2,350.41,3,214,4568.48,0.6865,1,2023-02-10 02:49:00
1,45.32,46648.03,0,1,11,47.14,1,78,297.39,0.5322,1,2023-03-26 22:32:00
2,32.25,80244.56,0,0,7,160.14,2,59,4792.40,0.4924,0,2023-08-05 12:29:00
3,35.41,24611.99,0,0,3,340.38,4,143,3318.08,0.5503,0,2023-01-22 19:26:00
4,57.80,27154.09,1,0,1,149.80,0,227,573.20,0.2208,0,2023-08-20 12:11:00

In [23]:
### get shape
get_shape(num_cols_valid)

(10000, 12)

##### *************** saving the data *****************

In [24]:
### setting up the respective paths to save the data
cat_cols_train_path = '../data/split_features/cat_cols_train.csv'
num_cols_train_path = '../data/split_features/num_cols_train.csv'
cat_cols_valid_path = '../data/split_features/cat_cols_valid.csv'
num_cols_valid_path = '../data/split_features/num_cols_valid.csv'

In [25]:
### saving them
save_data(cat_cols_train, cat_cols_train_path)
save_data(num_cols_train, num_cols_train_path)
save_data(cat_cols_valid, cat_cols_valid_path)
save_data(num_cols_valid, num_cols_valid_path)

In [26]:
### veryfying if everything went through
cat_cols_train = load_data(cat_cols_train_path)
cat_cols_train.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,ATM Withdrawal,Tablet,London,Travel,Mastercard,PIN
1,Bank Transfer,Mobile,New York,Electronics,Visa,OTP
2,ATM Withdrawal,Tablet,Sydney,Electronics,Mastercard,OTP
3,Online,Mobile,London,Travel,Discover,PIN
4,Online,Mobile,Sydney,Groceries,Amex,Password

In [ ]:
### check the shape
get_shape(cat_cols_train)

(40000, 6)

In [ ]:
### numerical train columns
num_cols_train = load_data(num_cols_train_path)
num_cols_train.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Fraud_Label,Timestamp
0,80.39,32068.28,0,0,5,112.75,4,142,3674.33,0.3668,0,1,2023-04-13 16:02:00
1,196.60,94961.81,0,0,8,199.95,1,32,796.99,0.4866,0,0,2023-03-27 05:02:00
2,21.88,39354.55,0,0,7,234.75,2,203,2286.33,0.2961,1,0,2023-09-27 23:30:00
3,121.23,46138.99,0,0,8,344.98,2,137,4924.98,0.3362,0,0,2023-09-10 13:13:00
4,34.53,52750.58,0,0,6,456.77,1,8,4924.36,0.0804,0,0,2023-01-13 06:58:00

In [ ]:
### categorcial valid columns
cat_cols_valid = load_data(cat_cols_valid_path)
cat_cols_valid.head()

,Transaction_Type,Device_Type,Location,Merchant_Category,Card_Type,Authentication_Method
0,Online,Mobile,Sydney,Clothing,Mastercard,OTP
1,Bank Transfer,Mobile,New York,Travel,Amex,Password
2,ATM Withdrawal,Laptop,Tokyo,Restaurants,Amex,Password
3,POS,Tablet,Mumbai,Travel,Mastercard,OTP
4,Bank Transfer,Tablet,Sydney,Groceries,Visa,Biometric

In [ ]:
### verify the shape
get_shape(cat_cols_valid)

(10000, 6)

In [ ]:
### numerical valid columns
num_cols_valid = load_data(num_cols_valid_path)
num_cols_valid.head()

,Transaction_Amount,Account_Balance,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Age,Transaction_Distance,Risk_Score,Is_Weekend,Timestamp
0,19.98,1804.81,0,0,2,350.41,3,214,4568.48,0.6865,1,2023-02-10 02:49:00
1,45.32,46648.03,0,1,11,47.14,1,78,297.39,0.5322,1,2023-03-26 22:32:00
2,32.25,80244.56,0,0,7,160.14,2,59,4792.40,0.4924,0,2023-08-05 12:29:00
3,35.41,24611.99,0,0,3,340.38,4,143,3318.08,0.5503,0,2023-01-22 19:26:00
4,57.80,27154.09,1,0,1,149.80,0,227,573.20,0.2208,0,2023-08-20 12:11:00

In [ ]:
### check the shape
get_shape(num_cols_valid)

(10000, 12)