## Split data : Raw to split

In [1]:
### autoreloader
%load_ext autoreload
%autoreload 2

In [2]:
### importing the sys path
import sys
sys.path.append('../')

In [7]:
### importing the function from the src files
from src.data.load_data import load_data, get_info, get_nan_duplicates_shape, get_shape, save_data, drop_col, get_unique, get_value_counts
from src.processing.split_data import split_data_global

In [4]:
### setting up the path for the data
df_path = '../data/raw/fraud-detection-raw.csv'

In [5]:
### loading the data
df = load_data(df_path)
df.head()

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,...,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,TXN_33553,USER_1834,39.79,POS,2023-08-14 19:30:00,93213.17,Laptop,Sydney,Travel,0,...,7,437.63,3,Amex,65,883.17,Biometric,0.8494,0,0
1,TXN_9427,USER_7875,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,Mobile,New York,Clothing,0,...,13,478.76,4,Mastercard,186,2203.36,Password,0.0959,0,1
2,TXN_199,USER_2734,28.96,Online,2023-06-20 15:25:00,1588.96,Tablet,Mumbai,Restaurants,0,...,14,50.01,4,Visa,226,1909.29,Biometric,0.8400,0,1
3,TXN_12447,USER_2617,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,Tablet,New York,Clothing,0,...,8,182.48,4,Visa,76,1311.86,OTP,0.7935,0,1
4,TXN_39489,USER_2014,31.28,POS,2023-11-11 23:44:00,92354.66,Mobile,Mumbai,Electronics,0,...,14,328.69,4,Mastercard,140,966.98,Password,0.3819,1,1

In [6]:
### checking the nan_duplicates and shape
get_nan_duplicates_shape(df)

shape : (50000, 21)
duplicate values : 0
Transaction_ID                  0
User_ID                         0
Transaction_Amount              0
Transaction_Type                0
Timestamp                       0
Account_Balance                 0
Device_Type                     0
Location                        0
Merchant_Category               0
IP_Address_Flag                 0
Previous_Fraudulent_Activity    0
Daily_Transaction_Count         0
Avg_Transaction_Amount_7d       0
Failed_Transaction_Count_7d     0
Card_Type                       0
Card_Age                        0
Transaction_Distance            0
Authentication_Method           0
Risk_Score                      0
Is_Weekend                      0
Fraud_Label                     0
dtype: int64

In [33]:
### checking the df_info
get_info(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Transaction_ID                50000 non-null  object
 1   User_ID                       50000 non-null  object
 2   Transaction_Amount            50000 non-null  float64
 3   Transaction_Type              50000 non-null  object
 4   Timestamp                     50000 non-null  object
 5   Account_Balance               50000 non-null  float64
 6   Device_Type                   50000 non-null  object
 7   Location                      50000 non-null  object
 8   Merchant_Category             50000 non-null  object
 9   IP_Address_Flag               50000 non-null  int64
 10  Previous_Fraudulent_Activity  50000 non-null  int64
 11  Daily_Transaction_Count       50000 non-null  int64
 12  Avg_Transaction_Amount_7d     50000 non-null  float64
 13  Failed_Transaction_Count_7d   50000 non-null  int64
 14  Card_Type                     50000 non-null  object
 15  Card_Age                      50000 non-null  int64
 16  Transaction_Distance          50000 non-null  float64
 17  Authentication_Method         50000 non-null  object
 18  Risk_Score                    50000 non-null  float64
 19  Is_Weekend                    50000 non-null  int64
 20  Fraud_Label                   50000 non-null  int64
dtypes: float64(5), int64(7), object(9)
memory usage: 8.0+ MB

In [43]:
### checking the value counts of the target feature (since it's a classification problem)
get_value_counts(df, 'Fraud_Label')

Fraud_Label
0    33933
1    16067
Name: count, dtype: int64

In [34]:
### checking the Transaction id column
get_value_counts(df, 'Transaction_ID')

Transaction_ID
TXN_33553    1
TXN_45900    1
TXN_35844    1
TXN_3325     1
TXN_6283     1
            ..
TXN_6725     1
TXN_45945    1
TXN_37967    1
TXN_16019    1
TXN_15795    1
Name: count, Length: 50000, dtype: int64

In [35]:
### checking the user id column
get_value_counts(df, 'User_ID')

User_ID
USER_6599    16
USER_3925    16
USER_9998    16
USER_1027    15
USER_5014    15
             ..
USER_5685     1
USER_1806     1
USER_8563     1
USER_5057     1
USER_5580     1
Name: count, Length: 8963, dtype: int64

In [24]:
### since the both Transaction and user id columns have unieque values, 
### I am dropping off the both of those 2 columns

In [36]:
### dropping off the Transaction_ID and User_ID column
drop_col(df, ['Transaction_ID', 'User_ID'])
df.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,39.79,POS,2023-08-14 19:30:00,93213.17,Laptop,Sydney,Travel,0,0,7,437.63,3,Amex,65,883.17,Biometric,0.8494,0,0
1,1.19,Bank Transfer,2023-06-07 04:01:00,75725.25,Mobile,New York,Clothing,0,0,13,478.76,4,Mastercard,186,2203.36,Password,0.0959,0,1
2,28.96,Online,2023-06-20 15:25:00,1588.96,Tablet,Mumbai,Restaurants,0,0,14,50.01,4,Visa,226,1909.29,Biometric,0.8400,0,1
3,254.32,ATM Withdrawal,2023-12-07 00:31:00,76807.20,Tablet,New York,Clothing,0,0,8,182.48,4,Visa,76,1311.86,OTP,0.7935,0,1
4,31.28,POS,2023-11-11 23:44:00,92354.66,Mobile,Mumbai,Electronics,0,1,14,328.69,4,Mastercard,140,966.98,Password,0.3819,1,1

In [8]:
### veryfying the shape again
get_shape(df)

(50000, 21)

In [38]:
### making the firstb split now into 2 : Train (80%) and valid (20%)
df_train, df_valid = split_data_global(df)

In [39]:
### veryfying the df_train
df_train.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,80.39,ATM Withdrawal,2023-04-13 16:02:00,32068.28,Tablet,London,Travel,0,0,5,112.75,4,Mastercard,142,3674.33,PIN,0.3668,0,1
1,196.60,Bank Transfer,2023-03-27 05:02:00,94961.81,Mobile,New York,Electronics,0,0,8,199.95,1,Visa,32,796.99,OTP,0.4866,0,0
2,21.88,ATM Withdrawal,2023-09-27 23:30:00,39354.55,Tablet,Sydney,Electronics,0,0,7,234.75,2,Mastercard,203,2286.33,OTP,0.2961,1,0
3,121.23,Online,2023-09-10 13:13:00,46138.99,Mobile,London,Travel,0,0,8,344.98,2,Discover,137,4924.98,PIN,0.3362,0,0
4,34.53,Online,2023-01-13 06:58:00,52750.58,Mobile,Sydney,Groceries,0,0,6,456.77,1,Amex,8,4924.36,Password,0.0804,0,0

In [40]:
### veryfying the df_train shape
get_shape(df_train)

(40000, 19)

In [52]:
### checking the balance of the classes of the target feature
get_value_counts(df_train, 'Fraud_Label')

Fraud_Label
0    27168
1    12832
Name: count, dtype: int64

In [41]:
### checking the df_valid
df_valid.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,19.98,Online,2023-02-10 02:49:00,1804.81,Mobile,Sydney,Clothing,0,0,2,350.41,3,Mastercard,214,4568.48,OTP,0.6865,1,0
1,45.32,Bank Transfer,2023-03-26 22:32:00,46648.03,Mobile,New York,Travel,0,1,11,47.14,1,Amex,78,297.39,Password,0.5322,1,0
2,32.25,ATM Withdrawal,2023-08-05 12:29:00,80244.56,Laptop,Tokyo,Restaurants,0,0,7,160.14,2,Amex,59,4792.40,Password,0.4924,0,0
3,35.41,POS,2023-01-22 19:26:00,24611.99,Tablet,Mumbai,Travel,0,0,3,340.38,4,Mastercard,143,3318.08,OTP,0.5503,0,1
4,57.80,Bank Transfer,2023-08-20 12:11:00,27154.09,Tablet,Sydney,Groceries,1,0,1,149.80,0,Visa,227,573.20,Biometric,0.2208,0,0

In [42]:
### checking the df_valid shape
get_shape(df_valid)

(10000, 19)

In [51]:
### checking the balance of the classes of the target feature
get_value_counts(df_valid, 'Fraud_Label')

Fraud_Label
0    6765
1    3235
Name: count, dtype: int64

In [44]:
### from the valid data, I am separating the target feature (Fraud_Label) a side and storing it 
valid = df_valid.drop('Fraud_Label', axis = 1)
y_true_valid = df_valid['Fraud_Label']

In [45]:
### veryfying the both
valid.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend
0,19.98,Online,2023-02-10 02:49:00,1804.81,Mobile,Sydney,Clothing,0,0,2,350.41,3,Mastercard,214,4568.48,OTP,0.6865,1
1,45.32,Bank Transfer,2023-03-26 22:32:00,46648.03,Mobile,New York,Travel,0,1,11,47.14,1,Amex,78,297.39,Password,0.5322,1
2,32.25,ATM Withdrawal,2023-08-05 12:29:00,80244.56,Laptop,Tokyo,Restaurants,0,0,7,160.14,2,Amex,59,4792.40,Password,0.4924,0
3,35.41,POS,2023-01-22 19:26:00,24611.99,Tablet,Mumbai,Travel,0,0,3,340.38,4,Mastercard,143,3318.08,OTP,0.5503,0
4,57.80,Bank Transfer,2023-08-20 12:11:00,27154.09,Tablet,Sydney,Groceries,1,0,1,149.80,0,Visa,227,573.20,Biometric,0.2208,0

In [46]:
get_shape(valid)

(10000, 18)

In [48]:
### y_true_valid
y_true_valid.head()

0    0
1    0
2    0
3    1
4    0
Name: Fraud_Label, dtype: int64

In [53]:
### setting up the path to save the data
y_true_valid_path = '../data/split/y_true_valid.csv'
train_path = '../data/split/train.csv'
valid_path = '../data/split/valid.csv'

In [54]:
### saving up the all three
save_data(y_true_valid, y_true_valid_path)

In [ ]:
### saving up the train
save_data(df_train, train_path)

In [56]:
### saving up the valid (without the target feature)
save_data(valid, valid_path)

In [57]:
### veryfying if everything was correct
train = load_data(train_path)
train.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend,Fraud_Label
0,80.39,ATM Withdrawal,2023-04-13 16:02:00,32068.28,Tablet,London,Travel,0,0,5,112.75,4,Mastercard,142,3674.33,PIN,0.3668,0,1
1,196.60,Bank Transfer,2023-03-27 05:02:00,94961.81,Mobile,New York,Electronics,0,0,8,199.95,1,Visa,32,796.99,OTP,0.4866,0,0
2,21.88,ATM Withdrawal,2023-09-27 23:30:00,39354.55,Tablet,Sydney,Electronics,0,0,7,234.75,2,Mastercard,203,2286.33,OTP,0.2961,1,0
3,121.23,Online,2023-09-10 13:13:00,46138.99,Mobile,London,Travel,0,0,8,344.98,2,Discover,137,4924.98,PIN,0.3362,0,0
4,34.53,Online,2023-01-13 06:58:00,52750.58,Mobile,Sydney,Groceries,0,0,6,456.77,1,Amex,8,4924.36,Password,0.0804,0,0

In [58]:
### for the valid data
valid = load_data(valid_path)
valid.head()

,Transaction_Amount,Transaction_Type,Timestamp,Account_Balance,Device_Type,Location,Merchant_Category,IP_Address_Flag,Previous_Fraudulent_Activity,Daily_Transaction_Count,Avg_Transaction_Amount_7d,Failed_Transaction_Count_7d,Card_Type,Card_Age,Transaction_Distance,Authentication_Method,Risk_Score,Is_Weekend
0,19.98,Online,2023-02-10 02:49:00,1804.81,Mobile,Sydney,Clothing,0,0,2,350.41,3,Mastercard,214,4568.48,OTP,0.6865,1
1,45.32,Bank Transfer,2023-03-26 22:32:00,46648.03,Mobile,New York,Travel,0,1,11,47.14,1,Amex,78,297.39,Password,0.5322,1
2,32.25,ATM Withdrawal,2023-08-05 12:29:00,80244.56,Laptop,Tokyo,Restaurants,0,0,7,160.14,2,Amex,59,4792.40,Password,0.4924,0
3,35.41,POS,2023-01-22 19:26:00,24611.99,Tablet,Mumbai,Travel,0,0,3,340.38,4,Mastercard,143,3318.08,OTP,0.5503,0
4,57.80,Bank Transfer,2023-08-20 12:11:00,27154.09,Tablet,Sydney,Groceries,1,0,1,149.80,0,Visa,227,573.20,Biometric,0.2208,0

In [59]:
### for the y_true_valie
y_true_valid = load_data(y_true_valid_path)
y_true_valid.head()

   Fraud_Label
0            0
1            0
2            0
3            1
4            0